### ISSUE TITLE
Force push systemd-v249 into a main branch

### ISSUE THREAD

**Issue by msekletar** [redhat-plumbers/systemd-rhel9#12]
Once https://gitlab.com/redhat/centos-stream/rpms/systemd/-/merge_requests/26 is merged we need to force push main branch in this repo to make sure that state of c9s dist-git and this repository correspond to each other.

In the MR I've dropped all current downstream patches except patch from https://github.com/redhat-plumbers/systemd-rhel9/pull/5. Hence the new state of this repo should be systemd-v249 plus one commit from #5.

**Comment by jamacku** [comment]
@msekletar Could you please review the ``main branch`` if it's correctly rebased to ``v249``? Thanks.

**Comment by msekletar** [comment]
Content of the `main` branch seems correct. Closing the issue.
