### ISSUE TITLE
Unprivileged systemd-nspawn appears to be borked on the latest main

### ISSUE THREAD

**Issue by mrc0mmand** [redhat-plumbers/systemd-rhel9#55]
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > CentOS 8 Stream

I'm not sure what's changed, but when running CentOS CI on the latest main, systemd-nspawn keep dying when running tests in unprivileged containers:
```
+ env --unset=UNIFIED_CGROUP_HIERARCHY --unset=SYSTEMD_NSPAWN_UNIFIED_HIERARCHY timeout --foreground 600 /root/systemd/build/systemd-nspawn --register=no --kill-signal=SIGKILL --directory=/var/tmp/systemd-test-TEST-01-BASIC/unprivileged-nspawn-root --setenv=SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-01.units:/usr/lib/systemd/tests/testdata/units: -U --private-network --machine=TEST-01-BASIC /usr/lib/systemd/systemd systemd.unit=testsuite.target systemd.wants=testsuite-01.service systemd.wants=end.service user_namespace.enable=1 systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=1
Spawning container TEST-01-BASIC on /var/tmp/systemd-test-TEST-01-BASIC/unprivileged-nspawn-root.
Press ^] three times within 1s to kill container.
Selected user namespace base 590217216 and range 65536.
Failed to set up ID mapped mounts: Operation not permitted
Short read while reading cgroup mode (0 bytes). The child is most likely dead.
E: nspawn failed with exit code 1
```

Example jobs:
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/rhel9-centos9/90/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/rhel9-centos9/91/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/rhel9-centos9/92/artifact//systemd-centos-ci/index.html
  * https://jenkins-systemd.apps.ocp.ci.centos.org/job/rhel9-centos9/93/artifact//systemd-centos-ci/index.html

/cc @dtardon @jamacku

**Comment by dtardon** [comment]
Reproducer:

`# systemd-run -D /var/lib/machines/test -U`

(It doesn't matter what is in the container.) Somewhat surprisingly, this is not caused by SELinux.

**Comment by mrc0mmand** [comment]
Maybe related https://github.com/systemd/systemd/issues/20989#issuecomment-997020912
