### ISSUE TITLE
Backport `udevadm wait` & `udevadm lock` stuff

### ISSUE THREAD

**Issue by mrc0mmand** [redhat-plumbers/systemd-rhel9#96]
It would be great to have this in RHEL 9 (especially for making tests more reliable, like TEST-64-UDEV-STORAGE and TEST-58-REPART), however, it might pull in a lot of other stuff.

Main PRs:
 - https://github.com/systemd/systemd/pull/22872
 - https://github.com/systemd/systemd/pull/22867

Follow-ups:
 - https://github.com/systemd/systemd/pull/22960 (depends on https://github.com/systemd/systemd/pull/22745)
 - https://github.com/systemd/systemd/pull/22964
 - https://github.com/systemd/systemd/pull/22996
 - and more (probably)

**Comment by jamacku** [comment]
Done via rebase to v252.
